/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/airplane/newm.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/newm.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Airplane1.geometry} material={materials.lambert4SG} />
      <mesh geometry={nodes.Wheel4.geometry} material={materials.lambert4SG} />
      <mesh geometry={nodes.Wheel3.geometry} material={materials.lambert4SG} />
      <mesh geometry={nodes.Wheel6.geometry} material={materials.lambert4SG} />
      <mesh geometry={nodes.Wheel5.geometry} material={materials.lambert4SG} />
      <mesh geometry={nodes.Wheel2.geometry} material={materials.lambert4SG} />
      <mesh geometry={nodes.Wheel1.geometry} material={materials.lambert4SG} />
    </group>
  )
}

useGLTF.preload('/newm.glb')
